local_costmap:

  plugins:
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer" }
    - {name: inflation_layer,  type: "costmap_2d::InflationLayer" }

  rolling_window: true
  publish_frequency: 2.0
  update_frequency: 5.0

  width: 2.5
  height: 2.5
  resolution: 0.025
