#!/usr/bin/env python
import subprocess
from subprocess import PIPE
import os


KNOWN_NVIDIA_ERRORS = [
    ("Failed to initialize NVML: Driver/library version mismatch"),
    ("NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. "
     "Make sure that the latest NVIDIA driver is installed and running."),
]


def is_nvidia():
    return False
    try:
        everything, _ = subprocess.Popen(["nvidia-smi", "--query-gpu=driver_version", "--format=noheader,csv"],
                                         stdout=PIPE, stderr=PIPE).communicate()
        everything = everything.strip()

        if everything in KNOWN_NVIDIA_ERRORS:
            return False
        
        return True
    except OSError:
        return False
    
    return False


def run_command(command):
    subprocess.call(command, shell=True)


def get_repo_root():
    return subprocess.check_output('git rev-parse --show-toplevel'.split()).strip()


def main():
    image_name = 'create_ros_kinetic_gazebo9'

    if is_nvidia():
        image_name = 'create_kinetic_nvidia'

    command = 'cd {} && make {}'.format(os.path.join(get_repo_root(), 'docker'), image_name)
    run_command(command)

if __name__ == '__main__':
    main()
