# If you want to rebuild all images, set this to --no-cache from the commandline
DOCKER_ARGS?=

.PHONY: create-melodic-gazebo9
create-melodic-gazebo9:
	docker build ${DOCKER_ARGS} -t create-melodic-gazebo9 create-melodic-gazebo9