<?xml version="1.0" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="sim_create_base">

    <xacro:property name="diffdrive_update_rate" value="40"/>
    <xacro:property name="wheel_torque" value="0.5"/>
    <xacro:property name="wheel_accel" value="0.5"/>

    <gazebo>
      <!-- Diff-drive controller -->
      <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
        <alwaysOn>true</alwaysOn>
        <rosDebugLevel>na</rosDebugLevel>
        <updateRate>${diffdrive_update_rate}</updateRate>
        <leftJoint>wheel_left_joint</leftJoint>
        <rightJoint>wheel_right_joint</rightJoint>
        <wheelSeparation>${wheel_separation}</wheelSeparation>
        <wheelDiameter>${wheel_radius * 2}</wheelDiameter>
        <wheelTorque>${wheel_torque}</wheelTorque>
        <wheelAcceleration>${wheel_accel}</wheelAcceleration>
        <commandTopic>cmd_vel</commandTopic>
        <odometryTopic>odom</odometryTopic>
        <odometryFrame>odom</odometryFrame>
        <robotBaseFrame>base_footprint</robotBaseFrame>
        <publishWheelTF>true</publishWheelTF>
        <publishOdomTF>true</publishOdomTF>
        <publishWheelJointState>true</publishWheelJointState>
        <odometrySource>world</odometrySource>
        <publishTf>true</publishTf>
      </plugin>

      <!-- Ground truth -->
      <plugin name="p3d_base_controller" filename="libgazebo_ros_p3d.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>60</updateRate>
        <robotNamespace>${robot_name}</robotNamespace>
        <bodyName>base_link</bodyName>
        <topicName>gts</topicName>
        <gaussianNoise>0</gaussianNoise>
        <frameName>map</frameName>
        <xyzOffset>0 0 0</xyzOffset>
        <rpyOffset>0 0 0</rpyOffset>
      </plugin>
    </gazebo>

    <!-- Virtual Wall detector -->
    <gazebo>
      <plugin name="virtual_wall_detector" filename="libvirtual_wall_detector.so">
        <updateRate>10</updateRate>
      </plugin>
    </gazebo>

    <!-- Bumpers -->
    <gazebo reference="bumper_link">
      <gravity>true</gravity>
      <self_collide>false</self_collide>
      <maxContacts>10</maxContacts>
      <sensor name='bumper_contact_sensor' type='contact'>
        <always_on>true</always_on>
        <update_rate>50</update_rate>
        <contact>
          <collision>bumper_link_collision</collision>
        </contact>
        <!-- Plugin -->
        <plugin name="create_bumper_controller" filename="libcreate_bumper_plugin.so">
          <frameName>base_footprint</frameName>
          <robotNamespace>${robot_name}</robotNamespace>
          <topicName>bumper</topicName>
        </plugin>
      </sensor>
    </gazebo>

    <!-- Cliff Publisher detector -->
    <gazebo>
      <plugin name="cliff_msg_publisher" filename="libcliff_msg_publisher.so">
        <updateRate>10</updateRate>
        <robotNumber>${robot_name}</robotNumber>
      </plugin>
    </gazebo>

  </xacro:macro>

</robot>
