robot_base_frame: base_link

transform_tolerance: 0.5

robot_radius: 0.18

observation_sources: bump scan

bump: {
  data_type: PointCloud2,
  topic: mobile_base/sensors/bumper_pointcloud,
  marking: true,
  clearing: false,
  min_obstacle_height: 0.0,
  max_obstacle_height: 0.1
}
scan: {
    sensor_frame: laser_link,
    data_type: LaserScan,
    topic: laser/scan,
    marking: true,
    clearing: true,
    obstacle_range: 6.0,
    raytrace_range: 10.0,
    min_obstacle_height: -0.1,
    max_obstacle_height: 6
}
