base_global_planner: "cuckoo_search_planner/CuckooSearchPlanner"

CuckooSearchPlanner:
  # Specifies the x size of an optional window to restrict the planner to, default 0.0
  planner_window_x: 0.0
  # Specifies the y size of an optional window to restrict the planner to, default 0.0
  planner_window_y: 0.0

  # If the goal is in an obstacle, the planer will plan to the nearest point in the radius of default_tolerance, default 0.0
  # The area is always searched, so could be slow for big values
  default_tolerance: 0.0
