base_global_planner: "jps/JumpPointSearchROS"

JumpPointSearchROS:
  debug: false
  dmp:
    potential_radius:
      x: 3.0
      y: 3.0
    search_radius:
      x: 0.5
      y: 0.5
    potential_map_range:
      x: 3.0
      y: 3.0
