# planners:
#   - name: 'GlobalPlanner'
#     type: 'global_planner/GlobalPlanner'
#   - name: 'SBPLLatticePlanner'
#     type: 'SBPLLatticePlanner'
# planner_patience: 10.0
# GlobalPlanner:
#   allow_unknown: false
#   default_tolerance: 0.0
#   visualize_potential: true
#   use_dijkstra: true
#   use_quadratic: false
#   use_grid_path: false
#   old_navfn_behaviour: false
#   lethal_cost: 253
#   neutral_cost: 66
#   cost_factor: 0.55
# SBPLLatticePlanner:
#   planner_type: 'ARAPlanner'
#   allocated_time: 20.0 # default: 10.0
#   initial_epsilon: 3.0
#   environment_type: 'XYThetaLattice' # The only environment supported
#   forward_search: true # default is false
#   nominalvel_mpersecs: 0.7
#   timetoturn45degsinplace_secs: 0.6
#   lethal_obstacle: 250

planners: 
  - name: 'planner'
    type: 'global_planner/GlobalPlanner'
planner:
  allow_unknown: false
  default_tolerance: 0.0
  visualize_potential: false
  use_dijkstra: true
  use_quadratic: false
  use_grid_path: false
  old_navfn_behaviour: false
